"use client";
import { ArrowUpRight, Check, Menu, X, Zap } from "lucide-react";
import { useState } from "react";

const faqs = [["Does Aster replace our existing tools?","No. It gives your existing work a clear operating layer, bringing decisions and handoffs into one view."],["Is this a real product?","Aster is a fictional concept created to demonstrate product design and frontend craft."],["Can teams tailor their workspace?","Yes. Every workflow has its own signals, owners, and review rhythm."]];
export default function Page() {
 const [open,setOpen]=useState<number|null>(null), [menu,setMenu]=useState(false);
 return <main><header><a className="brand" href="#top"><i/>ASTER</a><button className="menub" onClick={()=>setMenu(!menu)} aria-expanded={menu} aria-label={menu?"Close navigation":"Open navigation"}>{menu?<X/>:<Menu/>}</button><nav className={menu?"shown":""}><a href="#system">System</a><a href="#pricing">Plans</a><a href="#faq">FAQ</a><a className="navcta" href="#system">See the system <ArrowUpRight size={15}/></a></nav></header>
 <section id="top" className="hero"><div className="hero-copy"><p className="eyebrow"><span/>OPERATING CLARITY FOR MODERN TEAMS</p><h1>Work in motion,<br/><em>made visible.</em></h1><p className="lede">Aster turns decisions, owners, and due dates into one shared view of the work already moving through your team.</p><div className="actions"><a className="button" href="#system">See the system <ArrowUpRight size={17}/></a><a className="textlink" href="#system">Explore how it works <span>↓</span></a></div></div><Dashboard/></section>
 <section id="system" className="numbers"><p>Built around the moments where work gets lost: the handoff, the decision, the next move.</p><div><b>01</b><span>Trace every decision</span></div><div><b>02</b><span>Assign the next action</span></div><div><b>03</b><span>See progress without a status chase</span></div></section>
 <section className="feature"><div><p className="eyebrow">THE WORKING RECORD</p><h2>Meet work where it <em>actually happens.</em></h2></div><p>Turn a meeting note into an assigned next step, preserve the decision behind it, and make the deadline visible to everyone involved.</p></section>
 <section className="workflow"><article><b>01 / Capture</b><h3>Every signal has a home.</h3><p>Decisions, blockers and questions arrive with their context intact.</p></article><article><b>02 / Shape</b><h3>Give the next step an owner.</h3><p>Turn a loose thread into a next step, owner and meaningful due date.</p></article><article><b>03 / Move</b><h3>Review what changed.</h3><p>Open the project view and see the decisions and handoffs since your last check-in.</p></article></section>
 <section className="integrate"><p className="eyebrow">DESIGNED TO FIT IN</p><h2>Your tools, <em>less noise.</em></h2><div className="pills"><span>Calendar</span><span>Code</span><span>Messages</span><span>Docs</span><span>Meetings</span></div></section>
 <section id="pricing" className="pricing"><div><p className="eyebrow">SIMPLE BY DESIGN</p><h2>Start with a clearer Monday.</h2></div><article><p>TEAM SPACE</p><strong>$24 <small>/ person / month</small></strong><ul><li><Check/>Unlimited active work</li><li><Check/>Shared decision history</li><li><Check/>Personalized views</li></ul><a className="button" href="#system">Explore the system <ArrowUpRight size={17}/></a></article></section>
 <section id="faq" className="faq"><p className="eyebrow">QUESTIONS, ANSWERED</p><h2>A quieter way to run work.</h2>{faqs.map(([q,a],i)=><div className="faqitem" key={q}><button onClick={()=>setOpen(open===i?null:i)} aria-expanded={open===i}>{q}<span>{open===i?"−":"+"}</span></button>{open===i&&<p>{a}</p>}</div>)}</section>
 <section id="start" className="final"><Zap size={22}/><h2>Make the next move obvious.</h2><p>Aster is a fictional product concept demonstrating a focused project-operating interface.</p><a className="button" href="#system">Return to the system <ArrowUpRight size={17}/></a></section>
 <footer><a className="brand" href="#top"><i/>ASTER</a><span>Fictional concept · 2026</span><a href="#top">Back to top ↑</a></footer></main>
}
function Dashboard(){const[shared,setShared]=useState(false);return <div className="dash" aria-label="Illustration of Aster project dashboard"><div className="dtop"><span>Week 32 / Launch</span><span>● Live</span></div><aside><i/><i/><i/><i/></aside><div className="dmain"><div className="dashhead"><div><small>PROJECT PULSE</small><h3>Mobile onboarding</h3></div><button onClick={()=>{navigator.clipboard?.writeText(location.href);setShared(true)}}>{shared?"Link copied":"Share"}</button></div><div className="progress"><span>On track</span><i><b/></i><strong>68%</strong></div><div className="tasks"><p>Next moves <span>View all</span></p><div><b className="blue"/>Refine welcome flow <small>Today</small></div><div><b className="orange"/>Confirm translation review <small>Thu</small></div><div><b className="purple"/>Ship release notes <small>Fri</small></div></div></div><div className="note"><small>DECISION RECORDED</small><p>Keep setup to two steps.</p><span>AV · 10:42</span></div></div>}
